import NavBar from 'components/NavBar/NavBar';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect } from 'react';

const VendorsPage: NextPage = () => {
  const router = useRouter();

  useEffect(() => {
    console.log('useEffect happened');
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <div>
        <h1>This is the search page</h1>
      </div>
    </>
  );
};

export default VendorsPage;
