import Button from 'components/Button/Button';
import Search from 'components/Form/Input/Search/Search';
import StyledImg from 'components/Image/Image';
import NavBar from 'components/NavBar/NavBar';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import homeRings from 'public/home-rings.jpeg';
import { useId, useRef } from 'react';
import styles from './index.module.scss';

const searchPath = { pathname: '/search' };

const HomePage: NextPage = () => {
  const router = useRouter();
  const id = useId();
  const locationInputRef = useRef<HTMLInputElement>(null);

  const onSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const value = locationInputRef?.current?.value;
    if (!value) return;
    router.push({
      pathname: '/vendors',
      query: { q: value },
    });
  };

  return (
    <>
      <Head>
        <title>Humming Bird</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <body className={styles.main}>
        <h1 className={styles.heading1}>
          <span className={styles.headingSecondary}>Find</span>
          <span className={styles.headingPrimary}>Wedding Vendors</span>
          <span className={styles.headingSecondary}>that are the</span>
          <span className={styles.headingPrimary}>Perfect Fit</span>
        </h1>
        <h2 className={styles.heading2}>
          We match vendors on over 100 attributes to find one that fits you
        </h2>
        <form className={styles.form} onSubmit={onSubmit}>
          <Search id={id} ref={locationInputRef} placeholder="96185" />
          <Button text="Search" />
        </form>
        <StyledImg
          layout="intrinsic"
          className={styles.image}
          src={homeRings}
          alt="rings"
          width="700px"
          height="433px"
        />
      </body>
    </>
  );
};

export default HomePage;
